package com.hanbimei.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "THEME_ITEM".
 */
public class ThemeItem {

    private Long id;
    private Integer themeId;
    private Integer itemId;
    private String itemImg;
    private String itemUrl;
    private String itemTitle;
    private Integer itemPrice;
    private Integer itemCostPrice;
    private Integer itemDiscount;
    private Integer itemSoldAmount;
    private Boolean orMasterItem;
    private Integer collectCount;
    private String masterItemTag;
    private String masterItemImg;
    private String onShelvesAt;
    private String offShelvesAt;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ThemeItem() {
    }

    public ThemeItem(Long id) {
        this.id = id;
    }

    public ThemeItem(Long id, Integer themeId, Integer itemId, String itemImg, String itemUrl, String itemTitle, Integer itemPrice, Integer itemCostPrice, Integer itemDiscount, Integer itemSoldAmount, Boolean orMasterItem, Integer collectCount, String masterItemTag, String masterItemImg, String onShelvesAt, String offShelvesAt) {
        this.id = id;
        this.themeId = themeId;
        this.itemId = itemId;
        this.itemImg = itemImg;
        this.itemUrl = itemUrl;
        this.itemTitle = itemTitle;
        this.itemPrice = itemPrice;
        this.itemCostPrice = itemCostPrice;
        this.itemDiscount = itemDiscount;
        this.itemSoldAmount = itemSoldAmount;
        this.orMasterItem = orMasterItem;
        this.collectCount = collectCount;
        this.masterItemTag = masterItemTag;
        this.masterItemImg = masterItemImg;
        this.onShelvesAt = onShelvesAt;
        this.offShelvesAt = offShelvesAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getThemeId() {
        return themeId;
    }

    public void setThemeId(Integer themeId) {
        this.themeId = themeId;
    }

    public Integer getItemId() {
        return itemId;
    }

    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    public String getItemImg() {
        return itemImg;
    }

    public void setItemImg(String itemImg) {
        this.itemImg = itemImg;
    }

    public String getItemUrl() {
        return itemUrl;
    }

    public void setItemUrl(String itemUrl) {
        this.itemUrl = itemUrl;
    }

    public String getItemTitle() {
        return itemTitle;
    }

    public void setItemTitle(String itemTitle) {
        this.itemTitle = itemTitle;
    }

    public Integer getItemPrice() {
        return itemPrice;
    }

    public void setItemPrice(Integer itemPrice) {
        this.itemPrice = itemPrice;
    }

    public Integer getItemCostPrice() {
        return itemCostPrice;
    }

    public void setItemCostPrice(Integer itemCostPrice) {
        this.itemCostPrice = itemCostPrice;
    }

    public Integer getItemDiscount() {
        return itemDiscount;
    }

    public void setItemDiscount(Integer itemDiscount) {
        this.itemDiscount = itemDiscount;
    }

    public Integer getItemSoldAmount() {
        return itemSoldAmount;
    }

    public void setItemSoldAmount(Integer itemSoldAmount) {
        this.itemSoldAmount = itemSoldAmount;
    }

    public Boolean getOrMasterItem() {
        return orMasterItem;
    }

    public void setOrMasterItem(Boolean orMasterItem) {
        this.orMasterItem = orMasterItem;
    }

    public Integer getCollectCount() {
        return collectCount;
    }

    public void setCollectCount(Integer collectCount) {
        this.collectCount = collectCount;
    }

    public String getMasterItemTag() {
        return masterItemTag;
    }

    public void setMasterItemTag(String masterItemTag) {
        this.masterItemTag = masterItemTag;
    }

    public String getMasterItemImg() {
        return masterItemImg;
    }

    public void setMasterItemImg(String masterItemImg) {
        this.masterItemImg = masterItemImg;
    }

    public String getOnShelvesAt() {
        return onShelvesAt;
    }

    public void setOnShelvesAt(String onShelvesAt) {
        this.onShelvesAt = onShelvesAt;
    }

    public String getOffShelvesAt() {
        return offShelvesAt;
    }

    public void setOffShelvesAt(String offShelvesAt) {
        this.offShelvesAt = offShelvesAt;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
