package com.hanbimei.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hanbimei.entity.Theme;
import com.hanbimei.entity.ThemeItem;
import com.hanbimei.entity.Slider;
import com.hanbimei.entity.Ticket;
import com.hanbimei.entity.Adress;
import com.hanbimei.entity.User;
import com.hanbimei.entity.ShoppingGoods;

import com.hanbimei.dao.ThemeDao;
import com.hanbimei.dao.ThemeItemDao;
import com.hanbimei.dao.SliderDao;
import com.hanbimei.dao.TicketDao;
import com.hanbimei.dao.AdressDao;
import com.hanbimei.dao.UserDao;
import com.hanbimei.dao.ShoppingGoodsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig themeDaoConfig;
    private final DaoConfig themeItemDaoConfig;
    private final DaoConfig sliderDaoConfig;
    private final DaoConfig ticketDaoConfig;
    private final DaoConfig adressDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig shoppingGoodsDaoConfig;

    private final ThemeDao themeDao;
    private final ThemeItemDao themeItemDao;
    private final SliderDao sliderDao;
    private final TicketDao ticketDao;
    private final AdressDao adressDao;
    private final UserDao userDao;
    private final ShoppingGoodsDao shoppingGoodsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        themeDaoConfig = daoConfigMap.get(ThemeDao.class).clone();
        themeDaoConfig.initIdentityScope(type);

        themeItemDaoConfig = daoConfigMap.get(ThemeItemDao.class).clone();
        themeItemDaoConfig.initIdentityScope(type);

        sliderDaoConfig = daoConfigMap.get(SliderDao.class).clone();
        sliderDaoConfig.initIdentityScope(type);

        ticketDaoConfig = daoConfigMap.get(TicketDao.class).clone();
        ticketDaoConfig.initIdentityScope(type);

        adressDaoConfig = daoConfigMap.get(AdressDao.class).clone();
        adressDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        shoppingGoodsDaoConfig = daoConfigMap.get(ShoppingGoodsDao.class).clone();
        shoppingGoodsDaoConfig.initIdentityScope(type);

        themeDao = new ThemeDao(themeDaoConfig, this);
        themeItemDao = new ThemeItemDao(themeItemDaoConfig, this);
        sliderDao = new SliderDao(sliderDaoConfig, this);
        ticketDao = new TicketDao(ticketDaoConfig, this);
        adressDao = new AdressDao(adressDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        shoppingGoodsDao = new ShoppingGoodsDao(shoppingGoodsDaoConfig, this);

        registerDao(Theme.class, themeDao);
        registerDao(ThemeItem.class, themeItemDao);
        registerDao(Slider.class, sliderDao);
        registerDao(Ticket.class, ticketDao);
        registerDao(Adress.class, adressDao);
        registerDao(User.class, userDao);
        registerDao(ShoppingGoods.class, shoppingGoodsDao);
    }
    
    public void clear() {
        themeDaoConfig.getIdentityScope().clear();
        themeItemDaoConfig.getIdentityScope().clear();
        sliderDaoConfig.getIdentityScope().clear();
        ticketDaoConfig.getIdentityScope().clear();
        adressDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        shoppingGoodsDaoConfig.getIdentityScope().clear();
    }

    public ThemeDao getThemeDao() {
        return themeDao;
    }

    public ThemeItemDao getThemeItemDao() {
        return themeItemDao;
    }

    public SliderDao getSliderDao() {
        return sliderDao;
    }

    public TicketDao getTicketDao() {
        return ticketDao;
    }

    public AdressDao getAdressDao() {
        return adressDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ShoppingGoodsDao getShoppingGoodsDao() {
        return shoppingGoodsDao;
    }

}
