package com.hanbimei.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hanbimei.entity.Theme;
import com.hanbimei.entity.ThemeItem;
import com.hanbimei.entity.Slider;

import com.hanbimei.dao.ThemeDao;
import com.hanbimei.dao.ThemeItemDao;
import com.hanbimei.dao.SliderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig themeDaoConfig;
    private final DaoConfig themeItemDaoConfig;
    private final DaoConfig sliderDaoConfig;

    private final ThemeDao themeDao;
    private final ThemeItemDao themeItemDao;
    private final SliderDao sliderDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        themeDaoConfig = daoConfigMap.get(ThemeDao.class).clone();
        themeDaoConfig.initIdentityScope(type);

        themeItemDaoConfig = daoConfigMap.get(ThemeItemDao.class).clone();
        themeItemDaoConfig.initIdentityScope(type);

        sliderDaoConfig = daoConfigMap.get(SliderDao.class).clone();
        sliderDaoConfig.initIdentityScope(type);

        themeDao = new ThemeDao(themeDaoConfig, this);
        themeItemDao = new ThemeItemDao(themeItemDaoConfig, this);
        sliderDao = new SliderDao(sliderDaoConfig, this);

        registerDao(Theme.class, themeDao);
        registerDao(ThemeItem.class, themeItemDao);
        registerDao(Slider.class, sliderDao);
    }
    
    public void clear() {
        themeDaoConfig.getIdentityScope().clear();
        themeItemDaoConfig.getIdentityScope().clear();
        sliderDaoConfig.getIdentityScope().clear();
    }

    public ThemeDao getThemeDao() {
        return themeDao;
    }

    public ThemeItemDao getThemeItemDao() {
        return themeItemDao;
    }

    public SliderDao getSliderDao() {
        return sliderDao;
    }

}
