package com.hanbimei.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.hanbimei.entity.Theme;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "THEME".
*/
public class ThemeDao extends AbstractDao<Theme, Long> {

    public static final String TABLENAME = "THEME";

    /**
     * Properties of entity Theme.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Item_id = new Property(1, Integer.class, "item_id", false, "ITEM_ID");
        public final static Property ThemeImg = new Property(2, String.class, "themeImg", false, "THEME_IMG");
        public final static Property ThemeUrl = new Property(3, String.class, "themeUrl", false, "THEME_URL");
        public final static Property SortNum = new Property(4, Integer.class, "sortNum", false, "SORT_NUM");
        public final static Property Tag = new Property(5, String.class, "tag", false, "TAG");
    };


    public ThemeDao(DaoConfig config) {
        super(config);
    }
    
    public ThemeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"THEME\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ITEM_ID\" INTEGER," + // 1: item_id
                "\"THEME_IMG\" TEXT," + // 2: themeImg
                "\"THEME_URL\" TEXT," + // 3: themeUrl
                "\"SORT_NUM\" INTEGER," + // 4: sortNum
                "\"TAG\" TEXT);"); // 5: tag
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"THEME\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Theme entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer item_id = entity.getItem_id();
        if (item_id != null) {
            stmt.bindLong(2, item_id);
        }
 
        String themeImg = entity.getThemeImg();
        if (themeImg != null) {
            stmt.bindString(3, themeImg);
        }
 
        String themeUrl = entity.getThemeUrl();
        if (themeUrl != null) {
            stmt.bindString(4, themeUrl);
        }
 
        Integer sortNum = entity.getSortNum();
        if (sortNum != null) {
            stmt.bindLong(5, sortNum);
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(6, tag);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Theme readEntity(Cursor cursor, int offset) {
        Theme entity = new Theme( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // item_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // themeImg
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // themeUrl
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // sortNum
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // tag
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Theme entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setItem_id(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setThemeImg(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setThemeUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSortNum(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setTag(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Theme entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Theme entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
