package com.hanmimei.entity;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ADRESS".
 */
public class HMMAddress implements Serializable{

    private Long id;
    private Integer adress_id;
    private Integer user_id;
    private String name;
    private String city;
    private String phone;
    private String adress;
    private String other;
    private String idCard;
    private boolean isDefault = false;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public HMMAddress() {
    }

    public HMMAddress(Long id) {
        this.id = id;
    }
    public HMMAddress(String name, String city, String phone, String adress) {
        this.name = name;
        this.city = city;
        this.phone = phone;
        this.adress = adress;
    }


    public HMMAddress(Long id, Integer adress_id, Integer user_id, String name,
			String city, String phone, String adress, String other,
			String idCard, boolean isDefault) {
		super();
		this.id = id;
		this.adress_id = adress_id;
		this.user_id = user_id;
		this.name = name;
		this.city = city;
		this.phone = phone;
		this.adress = adress;
		this.other = other;
		this.idCard = idCard;
		this.isDefault = isDefault;
	}

	public String getIdCard() {
		return idCard;
	}
	public String getIdCardd() {
		return idCard.substring(0,5)+ "********" +idCard.substring(14, idCard.length());
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public boolean isDefault() {
		return isDefault;
	}

	public void setDefault(boolean isDefault) {
		this.isDefault = isDefault;
	}

	public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getAdress_id() {
        return adress_id;
    }

    public void setAdress_id(Integer adress_id) {
        this.adress_id = adress_id;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAdress() {
        return adress;
    }

    public void setAdress(String adress) {
        this.adress = adress;
    }

    public String getOther() {
        return other;
    }

    public void setOther(String other) {
        this.other = other;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
