package com.hanmimei.entity;

import java.math.BigDecimal;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "THEME_ITEM".
 */
public class HMMGoods {

	private Long id;
	private Integer themeId; //  主题id
	private Integer itemId; // 商品id
	private String itemImg; // 商品图片
	private String itemUrl; // 商品详情页链接
	private String itemTitle; // 商品标题
	private BigDecimal itemPrice; // 商品价格
	private BigDecimal itemDiscount; // 商品折扣
	private Integer itemSoldAmount; // 商品销售量
	private Boolean orMasterItem = false; // 是否是主题主打宣传商品
	private Integer collectCount; // 商品收藏数
	private String masterItemTag; // 如果是主打宣传商品，会需要tag json串
	private String masterItemImg; // 如果是主宣传商品图片url
	private String onShelvesAt; //
	private String offShelvesAt; //
	private BigDecimal invWeight; // 商品重量
	private String invArea; // 发货方式
	private Integer postalTaxRate; // 税率
	private String invCustoms; //保税区

	// 新添
	private String itemMasterImg;
	private BigDecimal itemSrcPrice; // 主sku原价
	private String state; // 商品状态
	

	// KEEP FIELDS - put your custom fields here
	// KEEP FIELDS END

	public String getItemMasterImg() {
		return itemMasterImg;
	}

	public Integer getPostalTaxRate() {
		return postalTaxRate;
	}

	public void setPostalTaxRate(Integer postalTaxRate) {
		this.postalTaxRate = postalTaxRate;
	}

	

	public String getInvArea() {
		return invArea;
	}

	public void setInvArea(String invArea) {
		this.invArea = invArea;
	}

	public void setItemMasterImg(String itemMasterImg) {
		this.itemMasterImg = itemMasterImg;
	}


	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public HMMGoods() {
	}

	public HMMGoods(Long id) {
		this.id = id;
	}


	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getThemeId() {
		return themeId;
	}

	public void setThemeId(Integer themeId) {
		this.themeId = themeId;
	}

	public Integer getItemId() {
		return itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	public String getItemImg() {
		return itemImg;
	}

	public void setItemImg(String itemImg) {
		this.itemImg = itemImg;
	}

	public String getItemUrl() {
		return itemUrl;
	}

	public void setItemUrl(String itemUrl) {
		this.itemUrl = itemUrl;
	}

	public String getItemTitle() {
		return itemTitle;
	}

	public void setItemTitle(String itemTitle) {
		this.itemTitle = itemTitle;
	}

	

	public Integer getItemSoldAmount() {
		return itemSoldAmount;
	}

	public void setItemSoldAmount(Integer itemSoldAmount) {
		this.itemSoldAmount = itemSoldAmount;
	}

	public Boolean getOrMasterItem() {
		return orMasterItem;
	}

	public void setOrMasterItem(Boolean orMasterItem) {
		this.orMasterItem = orMasterItem;
	}

	public Integer getCollectCount() {
		return collectCount;
	}

	public void setCollectCount(Integer collectCount) {
		this.collectCount = collectCount;
	}

	public String getMasterItemTag() {
		return masterItemTag;
	}

	public void setMasterItemTag(String masterItemTag) {
		this.masterItemTag = masterItemTag;
	}

	public String getMasterItemImg() {
		return masterItemImg;
	}

	public void setMasterItemImg(String masterItemImg) {
		this.masterItemImg = masterItemImg;
	}

	public String getOnShelvesAt() {
		return onShelvesAt;
	}

	public void setOnShelvesAt(String onShelvesAt) {
		this.onShelvesAt = onShelvesAt;
	}

	public String getOffShelvesAt() {
		return offShelvesAt;
	}

	public void setOffShelvesAt(String offShelvesAt) {
		this.offShelvesAt = offShelvesAt;
	}

	public String getInvCustoms() {
		return invCustoms;
	}

	public void setInvCustoms(String invCustoms) {
		this.invCustoms = invCustoms;
	}

	public BigDecimal getItemPrice() {
		return itemPrice;
	}

	public void setItemPrice(BigDecimal itemPrice) {
		this.itemPrice = itemPrice;
	}

	public BigDecimal getItemDiscount() {
		return itemDiscount;
	}

	public void setItemDiscount(BigDecimal itemDiscount) {
		this.itemDiscount = itemDiscount;
	}

	public BigDecimal getInvWeight() {
		return invWeight;
	}

	public void setInvWeight(BigDecimal invWeight) {
		this.invWeight = invWeight;
	}

	public BigDecimal getItemSrcPrice() {
		return itemSrcPrice;
	}

	public void setItemSrcPrice(BigDecimal itemSrcPrice) {
		this.itemSrcPrice = itemSrcPrice;
	}
	
	

	// KEEP METHODS - put your custom methods here
	// KEEP METHODS END

}
