package com.hanmimei.entity;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SLIDER".
 */
public class Slider implements Serializable{

    private Long id;
    private Integer slider_id;
    private String imgUrl;
    private String url;
    private String type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Slider() {
    }

    public Slider(Long id) {
        this.id = id;
    }

    public Slider(Long id, Integer slider_id, String imgUrl, String url, String type) {
        this.id = id;
        this.slider_id = slider_id;
        this.imgUrl = imgUrl;
        this.url = url;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSlider_id() {
        return slider_id;
    }

    public void setSlider_id(Integer slider_id) {
        this.slider_id = slider_id;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
