package com.hanmimei.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "THEME".
 */
public class Theme {

    private Long id;
    private Integer item_id;
    private String themeImg;
    private String themeUrl;
    private Integer width;
    private Integer height;
    private Integer sortNum;
    private String tag;
    private String type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Theme() {
    }

    public Theme(Long id) {
        this.id = id;
    }

    public Theme(Long id, Integer item_id, String themeImg, String themeUrl, Integer width, Integer height, Integer sortNum, String tag, String type) {
        this.id = id;
        this.item_id = item_id;
        this.themeImg = themeImg;
        this.themeUrl = themeUrl;
        this.width = width;
        this.height = height;
        this.sortNum = sortNum;
        this.tag = tag;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getItem_id() {
        return item_id;
    }

    public void setItem_id(Integer item_id) {
        this.item_id = item_id;
    }

    public String getThemeImg() {
        return themeImg;
    }

    public void setThemeImg(String themeImg) {
        this.themeImg = themeImg;
    }

    public String getThemeUrl() {
        return themeUrl;
    }

    public void setThemeUrl(String themeUrl) {
        this.themeUrl = themeUrl;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Integer getSortNum() {
        return sortNum;
    }

    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
