package com.hanmimei.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "TICKET".
 */
public class Ticket {

    private Long id;
    private Integer ticket_id;
    private Integer cut_price;
    private Integer more_price;
    private String use_date;
    private String whats;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Ticket() {
    }

    public Ticket(Long id) {
        this.id = id;
    }
    public Ticket(Integer cut_price, Integer more_price, String use_date) {
        this.cut_price = cut_price;
        this.more_price = more_price;
        this.use_date = use_date;
    }
    public Ticket(Long id, Integer ticket_id, Integer cut_price, Integer more_price, String use_date, String whats) {
        this.id = id;
        this.ticket_id = ticket_id;
        this.cut_price = cut_price;
        this.more_price = more_price;
        this.use_date = use_date;
        this.whats = whats;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTicket_id() {
        return ticket_id;
    }

    public void setTicket_id(Integer ticket_id) {
        this.ticket_id = ticket_id;
    }

    public Integer getCut_price() {
        return cut_price;
    }

    public void setCut_price(Integer cut_price) {
        this.cut_price = cut_price;
    }

    public Integer getMore_price() {
        return more_price;
    }

    public void setMore_price(Integer more_price) {
        this.more_price = more_price;
    }

    public String getUse_date() {
        return use_date;
    }

    public void setUse_date(String use_date) {
        this.use_date = use_date;
    }

    public String getWhats() {
        return whats;
    }

    public void setWhats(String whats) {
        this.whats = whats;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
