package com.hanmimei.dao;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;

import com.hanmimei.entity.ShoppingGoods;
import com.hanmimei.entity.Slider;
import com.hanmimei.entity.Theme;
import com.hanmimei.entity.Ticket;
import com.hanmimei.entity.User;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig themeDaoConfig;
    private final DaoConfig sliderDaoConfig;
    private final DaoConfig ticketDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig shoppingGoodsDaoConfig;

    private final ThemeDao themeDao;
    private final SliderDao sliderDao;
    private final TicketDao ticketDao;
    private final UserDao userDao;
    private final ShoppingGoodsDao shoppingGoodsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        themeDaoConfig = daoConfigMap.get(ThemeDao.class).clone();
        themeDaoConfig.initIdentityScope(type);


        sliderDaoConfig = daoConfigMap.get(SliderDao.class).clone();
        sliderDaoConfig.initIdentityScope(type);

        ticketDaoConfig = daoConfigMap.get(TicketDao.class).clone();
        ticketDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        shoppingGoodsDaoConfig = daoConfigMap.get(ShoppingGoodsDao.class).clone();
        shoppingGoodsDaoConfig.initIdentityScope(type);

        themeDao = new ThemeDao(themeDaoConfig, this);
        sliderDao = new SliderDao(sliderDaoConfig, this);
        ticketDao = new TicketDao(ticketDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        shoppingGoodsDao = new ShoppingGoodsDao(shoppingGoodsDaoConfig, this);

        registerDao(Theme.class, themeDao);
        registerDao(Slider.class, sliderDao);
        registerDao(Ticket.class, ticketDao);
        registerDao(User.class, userDao);
        registerDao(ShoppingGoods.class, shoppingGoodsDao);
    }
    
    public void clear() {
        themeDaoConfig.getIdentityScope().clear();
        sliderDaoConfig.getIdentityScope().clear();
        ticketDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        shoppingGoodsDaoConfig.getIdentityScope().clear();
    }

    public ThemeDao getThemeDao() {
        return themeDao;
    }

    public SliderDao getSliderDao() {
        return sliderDao;
    }

    public TicketDao getTicketDao() {
        return ticketDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ShoppingGoodsDao getShoppingGoodsDao() {
        return shoppingGoodsDao;
    }

}
