package com.kakao.kakaogift.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ENTRY".
 */
public class Entry {

    private Long id;
    private String itemTarget;
    private String targetType;
    private String navText;
    private String imgUrl;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Entry() {
    }

    public Entry(Long id) {
        this.id = id;
    }

    public Entry(Long id, String itemTarget, String targetType, String navText, String imgUrl) {
        this.id = id;
        this.itemTarget = itemTarget;
        this.targetType = targetType;
        this.navText = navText;
        this.imgUrl = imgUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getItemTarget() {
        return itemTarget;
    }

    public void setItemTarget(String itemTarget) {
        this.itemTarget = itemTarget;
    }

    public String getTargetType() {
        return targetType;
    }

    public void setTargetType(String targetType) {
        this.targetType = targetType;
    }

    public String getNavText() {
        return navText;
    }

    public void setNavText(String navText) {
        this.navText = navText;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
